const H='https://www.hebcal.com';let view=new Date();view.setDate(1);let loc=JSON.parse(localStorage.getItem('luachLoc')||'null')||{name:'Vienna, Austria',lat:48.2082,lon:16.3738,tz:'Europe/Vienna'};let jewish=[],gEvents=[];let settings=JSON.parse(localStorage.getItem('luachSettings')||'null')||{shmaMethod:'gra',tfillaMethod:'gra',alotMethod:'hebcal',tzeitMethod:'7083'};
const $=s=>document.querySelector(s), pad=n=>String(n).padStart(2,'0'), iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, fmtTime=s=>s?new Intl.DateTimeFormat('he-IL',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:loc.tz}).format(new Date(s)):'—';
async function j(url){let r=await fetch(url);if(!r.ok)throw Error(r.status);return r.json()}
async function load(){ $('#locationName').textContent=loc.name.split(',')[0];let y=view.getFullYear(),m=view.getMonth()+1;let start=new Date(y,m-1,1),end=new Date(y,m,0);let hs=await j(`${H}/hebcal?v=1&cfg=json&start=${iso(start)}&end=${iso(end)}&maj=on&min=on&mod=on&nx=on&mf=on&ss=on&s=on&D=on&d=on&o=on&lg=he`);jewish=hs.items||[];render();loadToday()}
function evFor(date){return jewish.filter(x=>x.date===date)}
function hebFor(date){let d=new Date(date+'T12:00:00');try{return new Intl.DateTimeFormat('he-IL-u-ca-hebrew',{day:'numeric',month:'long'}).format(d).replace(/\\u200f/g,'')}catch{return ''}}
function render(){let y=view.getFullYear(),m=view.getMonth();$('#monthTitle').textContent=new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric'}).format(view);let first=new Date(y,m,1),last=new Date(y,m+1,0),offset=first.getDay(),cells=[];for(let i=-offset;i<42-offset;i++){let d=new Date(y,m,1+i),date=iso(d),ev=evFor(date),h=hebFor(date),holiday=ev.find(e=>['holiday','roshchodesh','fast'].includes(e.category));let cls='day'+(d.getMonth()!=m?' out':'')+(date===iso(new Date())?' today':'');let ge=gEvents.some(e=>(e.start?.date||e.start?.dateTime||'').startsWith(date));cells.push(`<div class="${cls}" data-date="${date}"><div class="gdate">${d.getDate()}</div><div class="hdate">${h||''}</div>${holiday?`<div class="holiday">${holiday.hebrew||holiday.title}</div>`:''}${ge?'<i class="event-dot"></i>':''}</div>`)}$('#grid').innerHTML=cells.join('');document.querySelectorAll('.day').forEach(el=>el.onclick=()=>openDay(el.dataset.date))}
async function loadToday(){let d=new Date(),date=iso(d);try{let [conv,z,cal]=await Promise.all([j(`${H}/converter?cfg=json&g2h=1&date=${date}`),j(`${H}/zmanim?cfg=json&date=${date}&latitude=${loc.lat}&longitude=${loc.lon}&tzid=${encodeURIComponent(loc.tz)}`),j(`${H}/hebcal?v=1&cfg=json&start=${date}&end=${date}&D=on&d=on&lg=he`)]);$('#todayHeb').textContent=conv.hebrew;$('#todayGreg').textContent=new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);let daf=cal.items?.find(x=>x.category==='dafyomi');$('#todayLearning').textContent=daf?`דף היומי: ${daf.hebrew||daf.title}`:'דף היומי';$('#sunset').textContent=fmtTime(z.times.sunset)}catch(e){$('#todayLearning').textContent='לא ניתן לטעון נתונים כרגע'}}
async function openDay(date){let d=new Date(date+'T12:00:00');let [conv,z,cal]=await Promise.all([j(`${H}/converter?cfg=json&g2h=1&date=${date}`),j(`${H}/zmanim?cfg=json&date=${date}&latitude=${loc.lat}&longitude=${loc.lon}&tzid=${encodeURIComponent(loc.tz)}`),j(`${H}/hebcal?v=1&cfg=json&start=${date}&end=${date}&maj=on&min=on&mod=on&nx=on&mf=on&ss=on&s=on&D=on&d=on&o=on&lg=he`)]);let t=z.times,daf=cal.items?.find(x=>x.category==='dafyomi'),events=cal.items?.filter(x=>x.category!=='dafyomi')||[],ge=gEvents.filter(e=>(e.start?.date||e.start?.dateTime||'').startsWith(date));let rows=[];if(settings.alotMethod==='hebcal'||settings.alotMethod==='both')rows.push(['עלות השחר',t.alotHaShachar]);if(settings.alotMethod==='dawn'||settings.alotMethod==='both')rows.push(['דמדומי בוקר',t.dawn]);rows.push(['משיכיר',t.misheyakir],['זריחה',t.sunrise]);if(settings.shmaMethod==='gra'||settings.shmaMethod==='both')rows.push(['סוף זמן ק״ש גר״א',t.sofZmanShma]);if(settings.shmaMethod==='mga'||settings.shmaMethod==='both')rows.push(['סוף זמן ק״ש מג״א',t.sofZmanShmaMGA]);if(settings.tfillaMethod==='gra'||settings.tfillaMethod==='both')rows.push(['סוף זמן תפילה גר״א',t.sofZmanTfilla]);if(settings.tfillaMethod==='mga'||settings.tfillaMethod==='both')rows.push(['סוף זמן תפילה מג״א',t.sofZmanTfillaMGA]);rows.push(['חצות',t.chatzot],['מנחה גדולה',t.minchaGedola],['מנחה קטנה',t.minchaKetana],['פלג המנחה',t.plagHaMincha],['שקיעה',t.sunset]);if(settings.tzeitMethod==='7083'||settings.tzeitMethod==='both')rows.push(['צאת הכוכבים 7.083°',t.tzeit7083deg]);if(settings.tzeitMethod==='dusk'||settings.tzeitMethod==='both')rows.push(['דמדומי ערב',t.dusk]);$('#dayContent').innerHTML=`<h2>${conv.hebrew}</h2><div>${new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d)}</div>${daf?`<h3>📖 דף היומי</h3><p>${daf.hebrew||daf.title}</p>`:''}${events.length?`<h3>✡️ בלוח</h3>${events.map(e=>`<p>${e.hebrew||e.title}</p>`).join('')}`:''}<h3>☀️ זמני היום · ${loc.name}</h3><div class="zmanim">${rows.map(([n,v])=>`<div class="z"><span>${n}</span><strong>${fmtTime(v)}</strong></div>`).join('')}</div>${ge.length?`<h3>🗓️ Google Calendar</h3>${ge.map(e=>`<p>${e.summary||'(ללא כותרת)'}</p>`).join('')}`:''}`;$('#dayDialog').showModal()}
$('#prev').onclick=()=>{view.setMonth(view.getMonth()-1);load()};$('#next').onclick=()=>{view.setMonth(view.getMonth()+1);load()};$('#todayBtn').onclick=()=>{view=new Date();view.setDate(1);load()};$('#locationBtn').onclick=()=>$('#locationDialog').showModal();
$('#settingsBtn').onclick=()=>{['shmaMethod','tfillaMethod','alotMethod','tzeitMethod'].forEach(k=>$('#'+k).value=settings[k]);$('#settingsDialog').showModal()};$('#saveSettings').onclick=()=>{settings={shmaMethod:$('#shmaMethod').value,tfillaMethod:$('#tfillaMethod').value,alotMethod:$('#alotMethod').value,tzeitMethod:$('#tzeitMethod').value};localStorage.setItem('luachSettings',JSON.stringify(settings));$('#settingsDialog').close()};
$('#locationForm').onsubmit=async e=>{e.preventDefault();let q=$('#cityInput').value.trim();$('#locationResults').textContent='מחפש…';try{let data=await j(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=8&language=he&format=json`);let rs=data.results||[];$('#locationResults').innerHTML=rs.map((r,i)=>`<button class="primary loc" data-i="${i}">${r.name}${r.admin1?', '+r.admin1:''}, ${r.country}</button>`).join('')||'לא נמצאו תוצאות';document.querySelectorAll('.loc').forEach(b=>b.onclick=()=>{let r=rs[+b.dataset.i];loc={name:`${r.name}, ${r.country}`,lat:r.latitude,lon:r.longitude,tz:r.timezone};localStorage.setItem('luachLoc',JSON.stringify(loc));$('#locationDialog').close();load()})}catch{$('#locationResults').textContent='שגיאה בחיפוש'}};
$('#googleBtn').onclick=()=>$('#googleDialog').showModal();$('#clientId').value=localStorage.getItem('googleClientId')||'';$('#saveClient').onclick=()=>{let id=$('#clientId').value.trim();localStorage.setItem('googleClientId',id);$('#googleStatus').innerHTML=id?'נשמר. לאחר פרסום האתר ניתן להשלים התחברות Google OAuth.':'יש להזין Client ID.'};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load().catch(console.error);
