const H='https://www.hebcal.com',GOOGLE_CLIENT_ID='739551110627-ftda0amfofrrvah9kcjk6nsorh305bfj.apps.googleusercontent.com';let view=new Date();view.setDate(1);let selectedDate=null,googleAccessToken=null,googleTokenClient=null;let loc=JSON.parse(localStorage.getItem('luachLoc')||'null')||{name:'Vienna, Austria',lat:48.2082,lon:16.3738,tz:'Europe/Vienna'};let jewish=[],gEvents=[];let settings=JSON.parse(localStorage.getItem('luachSettings')||'null')||{shmaMethod:'gra',tfillaMethod:'gra',alotMethod:'hebcal',tzeitMethod:'7083'};
const $=s=>document.querySelector(s), pad=n=>String(n).padStart(2,'0'), iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, fmtTime=s=>s?new Intl.DateTimeFormat('he-IL',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:loc.tz}).format(new Date(s)):'—';
async function j(url){let r=await fetch(url);if(!r.ok)throw Error(r.status);return r.json()}
async function load(){ $('#locationName').textContent=loc.name.split(',')[0];let y=view.getFullYear(),m=view.getMonth()+1;let start=new Date(y,m-1,1),end=new Date(y,m,0);let hs=await j(`${H}/hebcal?v=1&cfg=json&start=${iso(start)}&end=${iso(end)}&maj=on&min=on&mod=on&nx=on&mf=on&ss=on&s=on&D=on&d=on&o=on&lg=he`);jewish=hs.items||[];if(googleAccessToken)await loadGoogleEvents(start,end);render();loadToday()}
function evFor(date){return jewish.filter(x=>x.date===date)}
const hebNums=['','א׳','ב׳','ג׳','ד׳','ה׳','ו׳','ז׳','ח׳','ט׳','י׳','י״א','י״ב','י״ג','י״ד','ט״ו','ט״ז','י״ז','י״ח','י״ט','כ׳','כ״א','כ״ב','כ״ג','כ״ד','כ״ה','כ״ו','כ״ז','כ״ח','כ״ט','ל׳'];function hebFor(date){let d=new Date(date+'T12:00:00');try{let p=new Intl.DateTimeFormat('en-u-ca-hebrew',{day:'numeric'}).formatToParts(d),day=parseInt(p.find(x=>x.type==='day')?.value,10),month=new Intl.DateTimeFormat('he-IL-u-ca-hebrew',{month:'long'}).format(d).replace(/^ב/,'');return ((hebNums[day]||day)+' '+month).trim()}catch{return ''}}
function render(){let y=view.getFullYear(),m=view.getMonth();let first=new Date(y,m,1),last=new Date(y,m+1,0),offset=first.getDay(),cells=[];for(let i=-offset;i<42-offset;i++){let d=new Date(y,m,1+i),date=iso(d),ev=evFor(date),h=hebFor(date),holiday=ev.find(e=>['holiday','roshchodesh','fast'].includes(e.category));let cls='day'+(d.getMonth()!=m?' out':'')+(date===iso(new Date())?' today':'')+(selectedDate===date?' selected-date':'');let ge=gEvents.some(e=>(e.start?.date||e.start?.dateTime||'').startsWith(date));cells.push(`<div class="${cls}" data-date="${date}"><div class="gdate">${d.getDate()}</div><div class="hdate">${h||''}</div>${holiday?`<div class="holiday">${holiday.hebrew||holiday.title}</div>`:''}${ge?'<i class="event-dot"></i>':''}</div>`)}$('#grid').innerHTML=cells.join('');document.querySelectorAll('.day').forEach(el=>el.onclick=()=>openDay(el.dataset.date))}
async function loadToday(){let d=new Date(),date=iso(d),sat=new Date(d);sat.setDate(d.getDate()+((6-d.getDay()+7)%7));let satDate=iso(sat);try{let [conv,dafCal,weekCal]=await Promise.all([j(`${H}/converter?cfg=json&g2h=1&date=${date}`),j(`${H}/hebcal?v=1&cfg=json&start=${date}&end=${date}&F=on&lg=he`),j(`${H}/hebcal?v=1&cfg=json&start=${date}&end=${satDate}&s=on&maj=on&lg=he`)]);$('#todayHeb').textContent=conv.hebrew;$('#todayGreg').textContent=new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);let daf=dafCal.items?.find(x=>x.category==='dafyomi'||/Daf Yomi/i.test(x.title||'')),parasha=weekCal.items?.find(x=>x.category==='parashat');$('#todayLearning').textContent=daf?`דף היומי: ${daf.hebrew||daf.title}`:'דף היומי: —';$('#todayParasha').textContent=parasha?`פרשת השבוע: ${(parasha.hebrew||parasha.title).replace(/^פרשת\\s+/,'').replace(/^Parashat\\s+/i,'')}`:'פרשת השבוע: —'}catch(e){$('#todayLearning').textContent='דף היומי: לא זמין';$('#todayParasha').textContent='פרשת השבוע: לא זמינה'}}
async function openDay(date){let d=new Date(date+'T12:00:00');let [conv,z,cal]=await Promise.all([j(`${H}/converter?cfg=json&g2h=1&date=${date}`),j(`${H}/zmanim?cfg=json&date=${date}&latitude=${loc.lat}&longitude=${loc.lon}&tzid=${encodeURIComponent(loc.tz)}`),j(`${H}/hebcal?v=1&cfg=json&start=${date}&end=${date}&maj=on&min=on&mod=on&nx=on&mf=on&ss=on&s=on&D=on&d=on&o=on&lg=he`)]);let t=z.times,daf=cal.items?.find(x=>x.category==='dafyomi'),events=cal.items?.filter(x=>x.category!=='dafyomi')||[],ge=gEvents.filter(e=>(e.start?.date||e.start?.dateTime||'').startsWith(date));let rows=[];if(settings.alotMethod==='hebcal'||settings.alotMethod==='both')rows.push(['עלות השחר',t.alotHaShachar]);if(settings.alotMethod==='dawn'||settings.alotMethod==='both')rows.push(['דמדומי בוקר',t.dawn]);rows.push(['משיכיר',t.misheyakir],['זריחה',t.sunrise]);if(settings.shmaMethod==='gra'||settings.shmaMethod==='both')rows.push(['סוף זמן ק״ש גר״א',t.sofZmanShma]);if(settings.shmaMethod==='mga'||settings.shmaMethod==='both')rows.push(['סוף זמן ק״ש מג״א',t.sofZmanShmaMGA]);if(settings.tfillaMethod==='gra'||settings.tfillaMethod==='both')rows.push(['סוף זמן תפילה גר״א',t.sofZmanTfilla]);if(settings.tfillaMethod==='mga'||settings.tfillaMethod==='both')rows.push(['סוף זמן תפילה מג״א',t.sofZmanTfillaMGA]);rows.push(['חצות',t.chatzot],['מנחה גדולה',t.minchaGedola],['מנחה קטנה',t.minchaKetana],['פלג המנחה',t.plagHaMincha],['שקיעה',t.sunset]);if(settings.tzeitMethod==='7083'||settings.tzeitMethod==='both')rows.push(['צאת הכוכבים 7.083°',t.tzeit7083deg]);if(settings.tzeitMethod==='dusk'||settings.tzeitMethod==='both')rows.push(['דמדומי ערב',t.dusk]);$('#dayContent').innerHTML=`<h2>${conv.hebrew}</h2><div>${new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d)}</div>${daf?`<h3>📖 דף היומי</h3><p>${daf.hebrew||daf.title}</p>`:''}${events.length?`<h3>✡️ בלוח</h3>${events.map(e=>`<p>${e.hebrew||e.title}</p>`).join('')}`:''}<h3>☀️ זמני היום · ${loc.name}</h3><div class="zmanim">${rows.map(([n,v])=>`<div class="z"><span>${n}</span><strong>${fmtTime(v)}</strong></div>`).join('')}</div>${ge.length?`<h3>🗓️ Google Calendar</h3>${ge.map(e=>`<p>${e.summary||'(ללא כותרת)'}</p>`).join('')}`:''}`;$('#dayDialog').showModal()}
$('#prev').onclick=()=>{view.setMonth(view.getMonth()-1);load()};$('#next').onclick=()=>{view.setMonth(view.getMonth()+1);load()};$('#todayBtn').onclick=()=>{selectedDate=null;view=new Date();view.setDate(1);load()};$('#locationBtn').onclick=()=>{$('#menuDialog').close();$('#locationDialog').showModal()};
function openSettings(){['shmaMethod','tfillaMethod','alotMethod','tzeitMethod'].forEach(k=>$('#'+k).value=settings[k]);$('#settingsDialog').showModal()}$('#menuBtn').onclick=()=>$('#menuDialog').showModal();$('#menuSettingsBtn').onclick=()=>{$('#menuDialog').close();openSettings()};$('#saveSettings').onclick=()=>{settings={shmaMethod:$('#shmaMethod').value,tfillaMethod:$('#tfillaMethod').value,alotMethod:$('#alotMethod').value,tzeitMethod:$('#tzeitMethod').value};localStorage.setItem('luachSettings',JSON.stringify(settings));$('#settingsDialog').close()};
$('#locationForm').onsubmit=async e=>{e.preventDefault();let q=$('#cityInput').value.trim();$('#locationResults').textContent='מחפש…';try{let data=await j(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=8&language=he&format=json`);let rs=data.results||[];$('#locationResults').innerHTML=rs.map((r,i)=>`<button class="primary loc" data-i="${i}">${r.name}${r.admin1?', '+r.admin1:''}, ${r.country}</button>`).join('')||'לא נמצאו תוצאות';document.querySelectorAll('.loc').forEach(b=>b.onclick=()=>{let r=rs[+b.dataset.i];loc={name:`${r.name}, ${r.country}`,lat:r.latitude,lon:r.longitude,tz:r.timezone};localStorage.setItem('luachLoc',JSON.stringify(loc));$('#locationDialog').close();load()})}catch{$('#locationResults').textContent='שגיאה בחיפוש'}};
function updateGoogleUI(connected){$('#googleConnectBtn').hidden=connected;$('#googleDisconnectBtn').hidden=!connected;$('#googleStatus').textContent=connected?'מחובר. אירועי Google מוצגים בלוח.':'לא מחובר';$('#googleBtn').textContent=connected?'🗓️ Google Calendar ✓':'🗓️ Google Calendar'}
async function googleApi(path){let r=await fetch('https://www.googleapis.com/calendar/v3/'+path,{headers:{Authorization:'Bearer '+googleAccessToken}});if(r.status===401){googleAccessToken=null;gEvents=[];updateGoogleUI(false);throw Error('expired')}if(!r.ok)throw Error(r.status);return r.json()}
async function loadGoogleEvents(start,end){try{let list=await googleApi('users/me/calendarList?maxResults=250'),from=new Date(start),to=new Date(end);to.setDate(to.getDate()+1);let all=await Promise.all((list.items||[]).filter(c=>c.selected!==false).map(async c=>{let q='calendars/'+encodeURIComponent(c.id)+'/events?singleEvents=true&orderBy=startTime&timeMin='+encodeURIComponent(from.toISOString())+'&timeMax='+encodeURIComponent(to.toISOString())+'&maxResults=2500';let data=await googleApi(q);return (data.items||[]).map(e=>({...e,_calendar:c.summary,_calendarId:c.id}))}));gEvents=all.flat()}catch(e){if(String(e.message)!=='expired')$('#googleStatus').textContent='לא הצלחתי לטעון את אירועי Google Calendar.'}}
function ensureGoogleClient(){if(googleTokenClient||!window.google?.accounts?.oauth2)return;googleTokenClient=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:'https://www.googleapis.com/auth/calendar.readonly',callback:async r=>{if(r.error){$('#googleStatus').textContent='החיבור בוטל או נכשל.';return}googleAccessToken=r.access_token;updateGoogleUI(true);$('#googleStatus').textContent='מחובר. טוען אירועים…';await load();$('#googleStatus').textContent='מחובר. אירועי Google מוצגים בלוח.'}})}
$('#googleBtn').onclick=()=>{$('#menuDialog').close();ensureGoogleClient();updateGoogleUI(!!googleAccessToken);$('#googleDialog').showModal()};
$('#googleConnectBtn').onclick=()=>{ensureGoogleClient();if(!googleTokenClient){$('#googleStatus').textContent='Google עדיין נטען. נסה שוב בעוד רגע.';return}googleTokenClient.requestAccessToken({prompt:'consent'})};
$('#googleDisconnectBtn').onclick=()=>{if(googleAccessToken&&window.google?.accounts?.oauth2)google.accounts.oauth2.revoke(googleAccessToken,()=>{});googleAccessToken=null;gEvents=[];updateGoogleUI(false);render()};
const gMonths=['ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'],hMonths=[['Nisan','ניסן'],['Iyyar','אייר'],['Sivan','סיון'],['Tamuz','תמוז'],['Av','אב'],['Elul','אלול'],['Tishrei','תשרי'],['Cheshvan','חשוון'],['Kislev','כסלו'],['Tevet','טבת'],['Shvat','שבט'],['Adar','אדר'],['Adar I','אדר א׳'],['Adar II','אדר ב׳']];
function fillSelect(el,items,selected){el.innerHTML=items.map(x=>{let v=Array.isArray(x)?x[0]:x,l=Array.isArray(x)?x[1]:x;return `<option value="${v}"${String(v)===String(selected)?' selected':''}>${l}</option>`}).join('')}
function initGoTo(){let n=new Date(),hy=Number(new Intl.DateTimeFormat('en-u-ca-hebrew',{year:'numeric'}).formatToParts(n).find(p=>p.type==='year')?.value)||5787;fillSelect($('#gDay'),Array.from({length:31},(_,i)=>i+1),n.getDate());fillSelect($('#gMonth'),gMonths.map((x,i)=>[i+1,x]),n.getMonth()+1);fillSelect($('#gYear'),Array.from({length:201},(_,i)=>n.getFullYear()-100+i),n.getFullYear());fillSelect($('#hDay'),Array.from({length:30},(_,i)=>i+1),1);fillSelect($('#hMonth'),hMonths,'Tishrei');fillSelect($('#hYear'),Array.from({length:201},(_,i)=>hy-100+i),hy)}
$('#goToBtn').onclick=()=>{$('#menuDialog').close();initGoTo();$('#goToDialog').showModal()};$('#goCalendar').onchange=()=>{let heb=$('#goCalendar').value==='heb';$('#gregFields').hidden=heb;$('#hebFields').hidden=!heb};
$('#goSubmit').onclick=async()=>{let d;$('#goStatus').textContent='טוען…';try{if($('#goCalendar').value==='greg'){d=new Date(+$('#gYear').value,+$('#gMonth').value-1,+$('#gDay').value);if(d.getDate()!=+$('#gDay').value)throw Error('invalid')}else{let q=`${H}/converter?cfg=json&h2g=1&hy=${$('#hYear').value}&hm=${encodeURIComponent($('#hMonth').value)}&hd=${$('#hDay').value}`,x=await j(q);d=new Date(x.gy,x.gm-1,x.gd)}selectedDate=iso(d);view=new Date(d.getFullYear(),d.getMonth(),1);$('#goToDialog').close();await load();setTimeout(()=>{let el=document.querySelector(`.day[data-date="${iso(d)}"]`);if(el){el.classList.add('gotoFlash');el.scrollIntoView({block:'center',behavior:'smooth'})}},80)}catch{$('#goStatus').textContent='לא ניתן לעבור לתאריך הזה. בדוק את הבחירה.'}};
let touchStart=null,swiping=false,animating=false;const calendar=$('.calendar');
function swipeNavigate(dx,dy){if(animating)return;animating=true;let horizontal=Math.abs(dx)>Math.abs(dy),outClass,inClass;if(horizontal){if(dx>0){view.setFullYear(view.getFullYear()+1);outClass='swipe-out-right';inClass='swipe-in-left'}else{view.setFullYear(view.getFullYear()-1);outClass='swipe-out-left';inClass='swipe-in-right'}}else{if(dy>0){view.setMonth(view.getMonth()-1);outClass='swipe-out-down';inClass='swipe-in-down'}else{view.setMonth(view.getMonth()+1);outClass='swipe-out-up';inClass='swipe-in-down'}}calendar.className='calendar '+outClass;setTimeout(async()=>{await load();calendar.className='calendar '+inClass;setTimeout(()=>{calendar.className='calendar';animating=false;swiping=false},360)},220)}
calendar.addEventListener('touchstart',e=>{if(e.touches.length!==1||animating)return;let t=e.touches[0];touchStart={x:t.clientX,y:t.clientY,time:Date.now()};swiping=false},{passive:true});calendar.addEventListener('touchmove',e=>{if(!touchStart||e.touches.length!==1)return;let t=e.touches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;if(Math.hypot(dx,dy)>12){swiping=true;e.preventDefault()}},{passive:false});calendar.addEventListener('touchend',e=>{if(!touchStart)return;let t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y,elapsed=Date.now()-touchStart.time;touchStart=null;if(elapsed>1200||Math.max(Math.abs(dx),Math.abs(dy))<45){swiping=false;return}swipeNavigate(dx,dy)},{passive:true});calendar.addEventListener('click',e=>{if(swiping||animating){e.preventDefault();e.stopPropagation()}},true);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load().catch(console.error);
